config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get '*path', to: 'application#index'
  get'/', to: 'application#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:index]

# https://github.com/plataformatec/devise#controller-filters-and-helpers
#  before_action :authenticate_user!
#  def can_administer?
#    current_user.try(:admin?)
#  end

  def can_administer?
    return false unless current_user
    current_user.try(:admin?)
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<div id="app">
</div>
<div id="content">
  <p> <a href="https://medium.com/@hpux/rails-5-1-loves-javascript-a1d84d5318b">Rails 5.1</a> breaks new ground in provided integrated support for JavaScript within a Ruby on Rails application.  However, that support comes with additional complexity and changes from prior ways of managing JavaScript.

  To help you get used to the new way of doing things, this boilerplate "batteries included" application demonstrates how to build and deploy a complete modern, hybrid web application using Rails 5.1, React, and Heroku, including an ActiveAdmin console and Devise authentication.
  </p>
  <p>From this page you can:</p>
  <ul>
    <li> <%= link_to("Login", new_admin_user_session_path) %> as an Administrator</a></li>
    <li> <%= link_to("Review", admin_admin_users_path) %> ActiveAdmin Users</a></li>
    <li> <%= link_to("Logout", destroy_admin_user_session_path) %> from Devise</a></li>
  </ul>
  <p>Note that you will need a seperate Devise configuration for non-Admin users.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyRailsReactApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'app', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>